# Generated by Django 5.2.7 on 2025-11-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
