# Generated by Django 5.2.7 on 2025-10-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('imageUrl', models.CharField(blank=True, max_length=255)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('description_tg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachersPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishLanguage_ru', models.CharField(max_length=255)),
                ('englishLanguage_en', models.CharField(max_length=255)),
                ('englishLanguage_tg', models.CharField(max_length=255)),
                ('online_ru', models.TextField()),
                ('online_en', models.TextField()),
                ('online_tg', models.TextField()),
                ('from990_ru', models.CharField(max_length=50)),
                ('from990_en', models.CharField(max_length=50)),
                ('from990_tg', models.CharField(max_length=50)),
                ('weMonitor_ru', models.TextField()),
                ('weMonitor_en', models.TextField()),
                ('weMonitor_tg', models.TextField()),
                ('changeGoals_ru', models.TextField()),
                ('changeGoals_en', models.TextField()),
                ('changeGoals_tg', models.TextField()),
                ('selectTutor_ru', models.CharField(max_length=100)),
                ('selectTutor_en', models.CharField(max_length=100)),
                ('selectTutor_tg', models.CharField(max_length=100)),
                ('teachers', models.ManyToManyField(related_name='pages', to='teacher_page.teacher')),
            ],
        ),
    ]
