# Generated by Django 5.2.7 on 2025-11-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='description_tg',
            new_name='description_tj',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='changeGoals_tg',
            new_name='changeGoals_tj',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='englishLanguage_tg',
            new_name='englishLanguage_tj',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='from990_tg',
            new_name='from990_tj',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='online_tg',
            new_name='online_tj',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='selectTutor_tg',
            new_name='selectTutor_tj',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='weMonitor_tg',
            new_name='weMonitor_tj',
        ),
    ]
