# Generated by Django 5.2.7 on 2025-11-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_page', '0002_rename_description_tg_teacher_description_tj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_tj',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
