# Generated by Django 5.2.7 on 2025-11-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_page', '0003_rename_name_teacher_name_ru_teacher_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='teachers/videos/'),
        ),
    ]
