# Generated by Django 5.2.7 on 2025-11-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_page', '0004_remove_teacher_imageurl_teacher_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherspage',
            old_name='changeGoals_en',
            new_name='change_goals_en',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='changeGoals_ru',
            new_name='change_goals_ru',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='changeGoals_tj',
            new_name='change_goals_tj',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='englishLanguage_en',
            new_name='english_language_en',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='englishLanguage_ru',
            new_name='english_language_ru',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='englishLanguage_tj',
            new_name='english_language_tj',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='from990_en',
            new_name='from_990_en',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='from990_ru',
            new_name='from_990_ru',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='from990_tj',
            new_name='from_990_tj',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='selectTutor_en',
            new_name='select_tutor_en',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='selectTutor_ru',
            new_name='select_tutor_ru',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='selectTutor_tj',
            new_name='select_tutor_tj',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='weMonitor_en',
            new_name='we_monitor_en',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='weMonitor_ru',
            new_name='we_monitor_ru',
        ),
        migrations.RenameField(
            model_name='teacherspage',
            old_name='weMonitor_tj',
            new_name='we_monitor_tj',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='video',
        ),
        migrations.AddField(
            model_name='teacher',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
