# Generated by Django 5.2.7 on 2025-11-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_page', '0005_rename_changegoals_en_teacherspage_change_goals_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='video_url',
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/images/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='teachers/videos/'),
        ),
    ]
