# Generated by Django 5.2.7 on 2025-12-12 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0014_notificationadmin_code_alter_smscode_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationadmin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
