# Generated by Django 5.2.7 on 2025-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.TextField()),
                ('question_ru', models.TextField()),
                ('question_tj', models.TextField()),
                ('answer_en', models.TextField()),
                ('answer_ru', models.TextField()),
                ('answer_tj', models.TextField()),
            ],
        ),
    ]
