# Generated by Django 5.2.7 on 2025-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.JSONField(default=dict)),
                ('answer', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FAQText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.JSONField(default=dict)),
                ('ru', models.JSONField(default=dict)),
                ('tj', models.JSONField(default=dict)),
            ],
        ),
    ]
