# Generated by Django 5.2.7 on 2025-11-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swipper', models.JSONField(blank=True, default=list, null=True)),
                ('features', models.JSONField(blank=True, default=list, null=True)),
                ('whyUs', models.JSONField(blank=True, default=list, null=True)),
                ('stats', models.JSONField(blank=True, default=list, null=True)),
                ('partners', models.JSONField(blank=True, default=list, null=True)),
                ('testimonials', models.JSONField(blank=True, default=list, null=True)),
                ('gallery', models.JSONField(blank=True, default=list, null=True)),
                ('courses', models.JSONField(blank=True, default=list, null=True)),
                ('courseHeader', models.JSONField(blank=True, default=list, null=True)),
                ('otzivi', models.JSONField(blank=True, default=list, null=True)),
                ('infoSwiper', models.JSONField(blank=True, default=list, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
