# Generated by Django 5.2.7 on 2025-11-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='courseHeader',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='infoSwiper',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='whyUs',
        ),
        migrations.AddField(
            model_name='homepage',
            name='course_header',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_swiper',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_us',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='courses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='otzivi',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='partners',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='swipper',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='testimonials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
