# Generated by Django 5.2.7 on 2025-11-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_remove_homepage_courseheader_remove_homepage_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='course_header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='features',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='info_swiper',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='otzivi',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='swipper',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='why_us',
        ),
        migrations.AddField(
            model_name='homepage',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
