# Generated by Django 5.2.7 on 2025-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_course_feature_galleryitem_infoswiperitem_partner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiperitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='swiperitem',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='swiperitem',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='swiperitem',
            name='name_tj',
        ),
        migrations.RemoveField(
            model_name='swiperitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='swiperitem',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='swiperitem',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='swiperitem',
            name='title_tj',
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='name',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='title',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='swiperitem',
            name='image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
