# Generated by Django 5.2.7 on 2025-11-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_alter_swiperitem_options_remove_swiperitem_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='features/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='infoswiperitem',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='info_swiper/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stats/'),
        ),
        migrations.AlterField(
            model_name='swiperitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='swiper/'),
        ),
    ]
