# Generated by Django 5.2.7 on 2025-11-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_testimonial_age_testimonial_image_testimonial_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
