# Generated by Django 5.2.7 on 2025-11-23 08:25

import home_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_alter_testimonial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiperitem',
            name='name',
            field=models.CharField(max_length=255),

        ),
        migrations.AlterField(
            model_name='swiperitem',
            name='title',
            field=models.CharField(max_length=255),

        ),
    ]
