# Generated by Django 5.2.7 on 2025-11-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_alter_swiperitem_name_alter_swiperitem_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiperitem',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='swiperitem',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='swiperitem',
            old_name='title',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='name_tj',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='title_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='title_ru',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='title_tj',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
