# Generated by Django 5.2.7 on 2025-11-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_fix_swiper_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiperitem',
            options={},
        ),
        migrations.AlterField(
            model_name='swiperitem',
            name='href',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='swiperitem',
            name='name',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swiperitem',
            name='title',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
