# Generated by Django 5.2.7 on 2025-11-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0012_alter_swiperitem_options_alter_swiperitem_href_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiperitem',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='swiperitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='swiperitem',
            name='title',
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='name_tj',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='swiperitem',
            name='title_tj',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='swiperitem',
            name='href',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
