# Generated by Django 5.2.7 on 2025-11-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0013_alter_swiperitem_options_remove_swiperitem_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiperitem',
            options={},
        ),
        migrations.AlterField(
            model_name='swiperitem',
            name='title_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='swiperitem',
            name='title_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='swiperitem',
            name='title_tj',
            field=models.CharField(max_length=255),
        ),
    ]
