# Generated by Django 5.2.7 on 2025-11-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0014_alter_swiperitem_options_alter_swiperitem_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='review',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='video',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_ru',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_tj',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review_tj',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='age',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
