# Generated by Django 5.2.7 on 2025-11-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0015_remove_testimonial_name_remove_testimonial_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='title_tj',
        ),
    ]
